# permissions for end users to view nginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-viewer-role
rules:
- apiGroups:
  - nginxcontroller.my.domain
  resources:
  - nginxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nginxcontroller.my.domain
  resources:
  - nginxes/status
  verbs:
  - get
